### ISSUE TITLE
In VAB PAW it only says "Enable staging"

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/TacSelfDestruct#8]
IMHO it should tell a little more, like

> TacSelfDestruct: Enable staging

**Comment by linuxgurugamer** [comment]
Why?  it's on the self-destruct part, isn't it obvious enough?

**Comment by Gordon-Dry** [comment]
Well, when patching it into other parts, it's a "problem" ...

**Comment by linuxgurugamer** [comment]
I'll add a field which will let you tell it to add a prefix to the PAW line

**Comment by linuxgurugamer** [comment]
In latest release
